import { RoadmapData } from './types/roadmap';

export function getFallbackRoadmap(careerTitle: string = 'Full Stack Developer', careerId: string = 'career-fullstack-001'): RoadmapData {
  return {
    id: 'fallback-roadmap-001',
    user_id: 'candidate-user',
    career_id: careerId,
    career_title: careerTitle,
    title: `Path to ${careerTitle}`,
    description: 'Personalized 6-month mastery roadmap targeting critical skill gaps, framework architecture, and production hiring bars.',
    duration_months: 6,
    progress_percent: 34.0,
    status: 'ACTIVE',
    version: 1,
    hours_per_week: 10,
    learning_pace: 'balanced',
    career_readiness_score: 68.0,
    readiness_breakdown: {
      readiness_score: 68.0,
      skill_coverage: 72.0,
      assessment_fit: 84.0,
      resume_evidence: 61.0,
      project_readiness: 45.0,
      roadmap_completion: 34.0,
    },
    roadmap_intelligence: {
      verified_skills_count: 12,
      skill_gaps_count: 4,
      assessment_fit_pct: 84.0,
      resume_points_count: 6,
      target_career: careerTitle,
    },
    estimated_total_hours: 240.0,
    completed_hours: 81.6,
    estimated_completion_date: '2026-11-30',
    phases: [
      {
        id: 'phase_1',
        month: 1,
        title: 'Phase 1: Foundation',
        subtitle: 'Core Language Mastery & Memory Paradigms',
        description: `Master core languages, algorithms, data structures, and linting best practices required for ${careerTitle}.`,
        status: 'COMPLETED',
        progress_percent: 100.0,
        target_skills: ['Python Fundamentals', 'Data Structures', 'OOP'],
        items_count: 2,
        completed_items_count: 2,
      },
      {
        id: 'phase_2',
        month: 2,
        title: 'Phase 2: Core Skills',
        subtitle: 'Framework Architecture & Data Workflows',
        description: `Build end-to-end multi-tier architectures, schema optimization, and validation pipelines tailored to ${careerTitle}.`,
        status: 'IN_PROGRESS',
        progress_percent: 50.0,
        target_skills: ['FastAPI', 'PostgreSQL', 'SQLAlchemy ORM'],
        items_count: 2,
        completed_items_count: 1,
      },
      {
        id: 'phase_3',
        month: 3,
        title: 'Phase 3: Advanced',
        subtitle: 'Domain Algorithms & Deep System Design',
        description: 'Implement high-concurrency systems, asynchronous background workflows, caching, and specialized algorithms.',
        status: 'NOT_STARTED',
        progress_percent: 0.0,
        target_skills: ['Redis Caching', 'Async Event Queues', 'Performance Optimization'],
        items_count: 2,
        completed_items_count: 0,
      },
      {
        id: 'phase_4',
        month: 4,
        title: 'Phase 4: Deployment & Tooling',
        subtitle: 'Containerization, Cloud & CI/CD',
        description: 'Package production artifacts with Docker, configure automated CI/CD validation suites, and deploy to modern cloud infrastructure.',
        status: 'LOCKED',
        progress_percent: 0.0,
        target_skills: ['Docker Multi-stage Builds', 'GitHub Actions CI/CD', 'Cloud Deployment'],
        items_count: 2,
        completed_items_count: 0,
      },
      {
        id: 'phase_5',
        month: 5,
        title: 'Phase 5: Portfolio Projects',
        subtitle: 'Production Capstone & Proof of Competence',
        description: `Design and deliver an enterprise-grade portfolio project showcasing end-to-end ${careerTitle} qualifications.`,
        status: 'LOCKED',
        progress_percent: 0.0,
        target_skills: ['System Architecture Design', 'Production Capstone'],
        items_count: 2,
        completed_items_count: 0,
      },
      {
        id: 'phase_6',
        month: 6,
        title: 'Phase 6: Career Launch',
        subtitle: 'Interview Calibration & Technical Defense',
        description: 'Polish technical resume bullet points, rehearse system design simulations, and finalize live GitHub demo repositories.',
        status: 'LOCKED',
        progress_percent: 0.0,
        target_skills: ['Technical Interview Algorithms', 'System Design & Recruiter Portfolio'],
        items_count: 2,
        completed_items_count: 0,
      },
    ],
    milestones: [
      { id: 'm1', title: 'Foundations Complete', month: 1, completed: true },
      { id: 'm2', title: 'Core Architectural Mastery', month: 2, completed: false },
      { id: 'm3', title: 'Advanced Engineering Ready', month: 3, completed: false },
      { id: 'm4', title: 'Production Deployment Cleared', month: 4, completed: false },
      { id: 'm5', title: 'Portfolio Deliverable Built', month: 5, completed: false },
      { id: 'm6', title: 'Career Readiness Certified', month: 6, completed: false },
    ],
    items: [
      {
        id: 'item-101',
        month: 1,
        phase_id: 'phase_1',
        title: 'Month 1: Core Language Mastery Fundamentals',
        description: 'Master clean coding standards, typing annotations, and foundational computational complexity.',
        item_type: 'learning',
        priority: 'CRITICAL',
        status: 'COMPLETED',
        skills: ['Python Fundamentals', 'Data Structures'],
        tasks: [
          { id: 't1-1', text: 'Review modern language idioms and type annotations', done: true },
          { id: 't1-2', text: 'Set up strict linting, formatting, and test scaffolding', done: true },
          { id: 't1-3', text: 'Implement 10 core algorithmic and memory layout exercises', done: true },
        ],
        estimated_hours: 20.0,
        actual_hours: 20.0,
        item_order: 1,
        dependencies: [],
        resource_links: [
          { id: 'r1', title: 'Official Python 3 Documentation & Tutorial', url: 'https://docs.python.org/3/tutorial/', type: 'Documentation', is_completed: true },
          { id: 'r2', title: 'Real Python: Python Best Practices & OOP', url: 'https://realpython.com/', type: 'Tutorial', is_completed: true },
        ],
        is_completed: true,
        notes: 'Completed core OOP patterns and algorithmic complexity benchmarks.',
        completed_at: '2026-08-20T10:00:00Z',
      },
      {
        id: 'item-102',
        month: 1,
        phase_id: 'phase_1',
        title: 'Month 1 Lab: Software Paradigms Application',
        description: 'Hands-on practical implementation of custom data structures and automated unit tests.',
        item_type: 'practice',
        priority: 'HIGH',
        status: 'COMPLETED',
        skills: ['Data Structures', 'OOP'],
        tasks: [
          { id: 't2-1', text: 'Construct custom binary search tree and hash table modules', done: true },
          { id: 't2-2', text: 'Write comprehensive unit tests with 90%+ code coverage', done: true },
        ],
        estimated_hours: 20.0,
        actual_hours: 20.0,
        item_order: 2,
        dependencies: ['item-101'],
        resource_links: [
          { id: 'r3', title: 'Pytest Documentation & Automated Testing', url: 'https://docs.pytest.org/en/stable/', type: 'Documentation', is_completed: true },
        ],
        is_completed: true,
        notes: 'Published clean repo to GitHub with automated GitHub Actions testing.',
        completed_at: '2026-08-28T14:30:00Z',
      },
      {
        id: 'item-201',
        month: 2,
        phase_id: 'phase_2',
        title: 'Month 2: Framework Architecture Fundamentals',
        description: 'Design robust asynchronous API routes, request validation schemas, and database session lifecycles.',
        item_type: 'learning',
        priority: 'CRITICAL',
        status: 'COMPLETED',
        skills: ['FastAPI', 'PostgreSQL'],
        tasks: [
          { id: 't3-1', text: 'Design relational schemas and queries for FastAPI', done: true },
          { id: 't3-2', text: 'Implement asynchronous API endpoints with strict input validation', done: true },
          { id: 't3-3', text: 'Integrate JWT authentication and security headers', done: true },
        ],
        estimated_hours: 20.0,
        actual_hours: 20.0,
        item_order: 3,
        dependencies: ['item-102'],
        resource_links: [
          { id: 'r4', title: 'FastAPI Official Documentation & Tutorial', url: 'https://fastapi.tiangolo.com/tutorial/', type: 'Documentation', is_completed: true },
          { id: 'r5', title: 'PostgreSQL Documentation & Query Optimization', url: 'https://www.postgresql.org/docs/current/tutorial.html', type: 'Documentation', is_completed: true },
        ],
        is_completed: true,
        notes: 'Constructed multi-tier backend with async SQLAlchemy 2.0.',
        completed_at: '2026-09-04T18:15:00Z',
      },
      {
        id: 'item-202',
        month: 2,
        phase_id: 'phase_2',
        title: 'Month 2 Lab: Data Workflows Application',
        description: 'Build automated data processing pipelines, database indexes, and integration test suites.',
        item_type: 'practice',
        priority: 'HIGH',
        status: 'IN_PROGRESS',
        skills: ['SQLAlchemy ORM', 'Database Optimization'],
        tasks: [
          { id: 't4-1', text: 'Build automated data processing pipelines for relational persistence', done: true },
          { id: 't4-2', text: 'Write integration test suites with mocked external services', done: false },
          { id: 't4-3', text: 'Optimize slow database queries using composite indexes', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 10.0,
        item_order: 4,
        dependencies: ['item-201'],
        resource_links: [
          { id: 'r6', title: 'SQLAlchemy 2.0 Async Unified Tutorial', url: 'https://docs.sqlalchemy.org/en/20/tutorial/', type: 'Documentation', is_completed: false },
        ],
        is_completed: false,
        notes: '',
        started_at: '2026-09-05T09:00:00Z',
      },
      {
        id: 'item-301',
        month: 3,
        phase_id: 'phase_3',
        title: 'Month 3: Domain Algorithms Fundamentals',
        description: 'Master caching invalidation protocols, distributed locks, and asynchronous event pub/sub.',
        item_type: 'learning',
        priority: 'HIGH',
        status: 'NOT_STARTED',
        skills: ['Redis Caching', 'Async Event Queues'],
        tasks: [
          { id: 't5-1', text: 'Design high-throughput asynchronous handlers with Redis caching', done: false },
          { id: 't5-2', text: 'Perform concurrency benchmarks under simulated load', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 5,
        dependencies: ['item-202'],
        resource_links: [
          { id: 'r7', title: 'Redis Official Documentation & Patterns', url: 'https://redis.io/docs/', type: 'Documentation', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-302',
        month: 3,
        phase_id: 'phase_3',
        title: 'Month 3 Lab: Deep System Design Application',
        description: 'Construct a resilient background worker system with retry policies and dead-letter queues.',
        item_type: 'practice',
        priority: 'HIGH',
        status: 'LOCKED',
        skills: ['Performance Optimization'],
        tasks: [
          { id: 't6-1', text: 'Implement worker pool for deferred email and analytics tasks', done: false },
          { id: 't6-2', text: 'Document architecture decisions in formal ADR markdown', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 6,
        dependencies: ['item-301'],
        resource_links: [
          { id: 'r8', title: 'System Architecture & Design Patterns Reference', url: 'https://developer.mozilla.org/', type: 'Tutorial', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-401',
        month: 4,
        phase_id: 'phase_4',
        title: 'Month 4: Containerization & CI/CD Fundamentals',
        description: 'Build production Docker images, multistage build layers, and automated GitHub Actions verification.',
        item_type: 'learning',
        priority: 'HIGH',
        status: 'LOCKED',
        skills: ['Docker Multi-stage Builds', 'GitHub Actions CI/CD'],
        tasks: [
          { id: 't7-1', text: 'Create multi-stage Dockerfiles optimizing image size under 150MB', done: false },
          { id: 't7-2', text: 'Configure GitHub Actions CI/CD for automated linting & tests', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 7,
        dependencies: ['item-302'],
        resource_links: [
          { id: 'r9', title: 'Docker Getting Started Guide & Multi-Stage Builds', url: 'https://docs.docker.com/get-started/', type: 'Documentation', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-402',
        month: 4,
        phase_id: 'phase_4',
        title: 'Month 4 Lab: Cloud Deployment Application',
        description: 'Deploy containerized services to a secure cloud runtime with zero-downtime healthchecks.',
        item_type: 'practice',
        priority: 'HIGH',
        status: 'LOCKED',
        skills: ['Cloud Deployment'],
        tasks: [
          { id: 't8-1', text: 'Set up health check endpoints and uptime monitoring', done: false },
          { id: 't8-2', text: 'Execute rolling deployment simulation with zero downtime', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 8,
        dependencies: ['item-401'],
        resource_links: [
          { id: 'r10', title: 'GitHub Actions Guide & Workflows', url: 'https://docs.github.com/en/actions', type: 'Documentation', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-501',
        month: 5,
        phase_id: 'phase_5',
        title: 'Month 5: Production Capstone Architecture',
        description: 'Draft end-to-end architecture specification for capstone showcase matching target hiring bars.',
        item_type: 'project',
        priority: 'CRITICAL',
        status: 'LOCKED',
        skills: ['System Architecture Design'],
        tasks: [
          { id: 't9-1', text: 'Draft end-to-end architecture specification for capstone', done: false },
          { id: 't9-2', text: 'Build core business logic and full data persistence layer', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 9,
        dependencies: ['item-402'],
        resource_links: [
          { id: 'r11', title: 'GitHub Profile & README Best Practices', url: 'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile', type: 'Article', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-502',
        month: 5,
        phase_id: 'phase_5',
        title: 'Month 5 Lab: Production Capstone Engineering',
        description: 'Build interactive UI, live deployment link, and comprehensive documentation.',
        item_type: 'project',
        priority: 'CRITICAL',
        status: 'LOCKED',
        skills: ['Production Capstone'],
        tasks: [
          { id: 't10-1', text: 'Write end-to-end test suites verifying critical user journeys', done: false },
          { id: 't10-2', text: 'Deploy live working demo with publicly accessible URL', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 10,
        dependencies: ['item-501'],
        resource_links: [
          { id: 'r12', title: 'Full Stack Deployment Architecture', url: 'https://docs.python.org/3/', type: 'Documentation', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-601',
        month: 6,
        phase_id: 'phase_6',
        title: 'Month 6: Technical Interview Calibration',
        description: 'Complete algorithm benchmarks and mock system design simulations.',
        item_type: 'interview',
        priority: 'HIGH',
        status: 'LOCKED',
        skills: ['Technical Interview Algorithms'],
        tasks: [
          { id: 't11-1', text: 'Complete 15 medium technical algorithm problems', done: false },
          { id: 't11-2', text: 'Conduct mock system design interview covering data partitioning', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 11,
        dependencies: ['item-502'],
        resource_links: [
          { id: 'r13', title: 'LeetCode Technical Interview Explore Catalog', url: 'https://leetcode.com/explore/', type: 'Practice', is_completed: false },
        ],
        is_completed: false,
      },
      {
        id: 'item-602',
        month: 6,
        phase_id: 'phase_6',
        title: 'Month 6 Lab: Recruiter Portfolio Defense',
        description: 'Record video walkthrough, tailor ATS resume bullet points, and submit targeted applications.',
        item_type: 'resume',
        priority: 'HIGH',
        status: 'LOCKED',
        skills: ['System Design & Recruiter Portfolio'],
        tasks: [
          { id: 't12-1', text: 'Record 3-minute video walkthrough showcasing capstone portfolio', done: false },
          { id: 't12-2', text: 'Tailor LinkedIn headline, summary, and verified skill badges', done: false },
          { id: 't12-3', text: 'Submit 5 targeted applications to verified hiring companies', done: false },
        ],
        estimated_hours: 20.0,
        actual_hours: 0.0,
        item_order: 12,
        dependencies: ['item-601'],
        resource_links: [
          { id: 'r14', title: 'Tech Resume Guide & ATS Optimization', url: 'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile', type: 'Article', is_completed: false },
        ],
        is_completed: false,
      },
    ],
    next_best_action: {
      item_id: 'item-202',
      title: 'Continue: Month 2 Lab: Data Workflows Application',
      phase_id: 'phase_2',
      priority: 'HIGH',
      estimated_hours: 20.0,
      estimated_minutes: 45,
      reason: 'This task is currently in progress and targets SQLAlchemy ORM and Database Optimization.',
      action_label: 'Continue Task →',
      action_url: '/roadmap#item-item-202',
    },
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
  };
}
